name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: thijswm
          password: ${{ Docker.DOCKER_TOKEN }}
      - 
        name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      -
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: thijswm/tesla_solar_charger
      -
        name: Build docker image
        uses: docker/build-push-action@v6.12.0
        with:
          context: ./SolarCharger
          file: ./SolarCharger/server.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: true
